services:
  mongo:
    image: mongo
    # environment: 
    #   # 不要設密碼就不會開啟驗證，直接無帳號密碼登入，你給帳號密碼反而會報錯
    #   # Skip verification by not setting a password. Log in directly without credentials. Supplying a username and password will cause an error.
    #   # Use "mongodb://localhost:27017/" for login.
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - ./database/data:/data/db
    ports: 
      - '27017:27017'

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
